// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AvailableEncoders() {
  return window['go']['main']['App']['AvailableEncoders']();
}

export function AvailableHWAccels() {
  return window['go']['main']['App']['AvailableHWAccels']();
}

export function CancelFFmpegInstall() {
  return window['go']['main']['App']['CancelFFmpegInstall']();
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function ConfigPath() {
  return window['go']['main']['App']['ConfigPath']();
}

export function DetectFFmpeg() {
  return window['go']['main']['App']['DetectFFmpeg']();
}

export function GetFFmpegInfo() {
  return window['go']['main']['App']['GetFFmpegInfo']();
}

export function InstallFFmpeg() {
  return window['go']['main']['App']['InstallFFmpeg']();
}

export function MediaURL(arg1) {
  return window['go']['main']['App']['MediaURL'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PickDirectory(arg1) {
  return window['go']['main']['App']['PickDirectory'](arg1);
}

export function PickFFmpegPath() {
  return window['go']['main']['App']['PickFFmpegPath']();
}

export function PickFontFile() {
  return window['go']['main']['App']['PickFontFile']();
}

export function PickImageFile() {
  return window['go']['main']['App']['PickImageFile']();
}

export function PickMediaFile() {
  return window['go']['main']['App']['PickMediaFile']();
}

export function PickSaveFile(arg1, arg2) {
  return window['go']['main']['App']['PickSaveFile'](arg1, arg2);
}

export function PreparePreview(arg1) {
  return window['go']['main']['App']['PreparePreview'](arg1);
}

export function PreviewCommand(arg1) {
  return window['go']['main']['App']['PreviewCommand'](arg1);
}

export function ProbeMedia(arg1) {
  return window['go']['main']['App']['ProbeMedia'](arg1);
}

export function RegisterFile(arg1) {
  return window['go']['main']['App']['RegisterFile'](arg1);
}

export function SetFFmpegPath(arg1) {
  return window['go']['main']['App']['SetFFmpegPath'](arg1);
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}

export function SuggestOutputPath(arg1, arg2) {
  return window['go']['main']['App']['SuggestOutputPath'](arg1, arg2);
}

export function TaskBusy() {
  return window['go']['main']['App']['TaskBusy']();
}
