// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {media} from '../models';
import {main} from '../models';
import {task} from '../models';

export function AvailableEncoders():Promise<Record<string, boolean>>;

export function AvailableHWAccels():Promise<Array<string>>;

export function CancelFFmpegInstall():Promise<void>;

export function CancelTask(arg1:string):Promise<void>;

export function ConfigPath():Promise<string>;

export function DetectFFmpeg():Promise<media.FFmpegInfo>;

export function GetFFmpegInfo():Promise<media.FFmpegInfo>;

export function InstallFFmpeg():Promise<void>;

export function MediaURL(arg1:string):Promise<string>;

export function OpenDirectory(arg1:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PickDirectory(arg1:string):Promise<string>;

export function PickFFmpegPath():Promise<media.FFmpegInfo>;

export function PickFontFile():Promise<main.PickedFile>;

export function PickImageFile():Promise<main.PickedFile>;

export function PickMediaFile():Promise<main.PickedFile>;

export function PickSaveFile(arg1:string,arg2:string):Promise<string>;

export function PreparePreview(arg1:string):Promise<main.PreviewResult>;

export function PreviewCommand(arg1:task.Spec):Promise<main.CommandPreview>;

export function ProbeMedia(arg1:string):Promise<media.MediaInfo>;

export function RegisterFile(arg1:string):Promise<main.PickedFile>;

export function SetFFmpegPath(arg1:string):Promise<media.FFmpegInfo>;

export function StartTask(arg1:task.Spec):Promise<string>;

export function SuggestOutputPath(arg1:string,arg2:string):Promise<string>;

export function TaskBusy():Promise<boolean>;
